[package]
name = "minimal-api"
version = "0.0.1"
edition = "2024"
authors = ["Evan Gipson"]

[dependencies]
http = { path = "libs/http" }
http_attributes = { path = "libs/http_attributes" }
logger = { path = "libs/logger" }